Tasbir/urls.py
from django.contrib import admin
from django.urls import path, include
from photo_app.views import index
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('photo_app.urls')),
    path('users/',include('user_app.urls'))

]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

photo_app/urls.py
from django.contrib import admin
from django.urls import path
from photo_app.views import index, add, edit, profile, delete, profile_edit, search

app_name='photo_app'
urlpatterns = [
    path('', index,name='index'),   
    path('add', add,name='add'),
    path('profile_edit/', profile_edit, name='profile_edit'),
    path('profile/',profile, name='profile'),
    path('delete/<int:id>/',delete ,name='delete'),
    path('search',search, name='search')
    
]

user_app/urls.py
from django.contrib import admin
from django.urls import path
from user_app.views import display,login,logout
app_name= 'user'
urlpatterns = [
    # path('', index),
    path('display/',display, name='display'),
    path('login/',login, name="login"),
    path('logout/',logout, name="logout")
  
]

photo_app/models.py
from django.db import models
from user_app.models import UserModel

# Create your models here.

class PhotoModel(models.Model):
     photo = models.ImageField(upload_to='upload_pic')
     caption = models.TextField(blank=True,null=True)
     timestamp= models.DateTimeField(auto_now_add=True)
     upload_by= models.ForeignKey(UserModel,on_delete=models.CASCADE, related_name='uploaded_post')
     likes=models.PositiveIntegerField(default=0)

class CommentModel(models.Model):
    comment=models.TextField()
    timestamp= models.DateTimeField(auto_now_add=True)
    commented_by=models.ForeignKey(UserModel,on_delete=models.CASCADE, related_name='comments')
    parent_post=models.ForeignKey(PhotoModel,on_delete=models.CASCADE, related_name='comments')

user_app/models.py
from django.db import models

# Create your models here.
class UserModel(models.Model):
    name = models.CharField(max_length=255)
    username = models.CharField(max_length=255)
    email = models.EmailField(max_length=255)
    password = models.CharField(max_length=255)
    bio = models.TextField(max_length=255)
    photo= models.ImageField(upload_to="profile_pic")
    
    def __str__(self):
         return self.username

photo_app/forms.py
from django import forms 
from .models import PhotoModel,CommentModel

class PhotoForm(forms.ModelForm):
    class Meta:
        model = PhotoModel
        fields ='__all__'
class CommentForm(forms.ModelForm):
    class Meta:
        model =CommentModel
        fields = '__all__'

photo_app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import PhotoModel
from .forms import PhotoForm
from .models import UserModel

# Create your views here.
def index(request):
    if 'id' in request.session:
         upload = PhotoModel.objects.all()[:20]
         return render(request,'photo_app/index.html',{'upload':upload})
    else:
        return redirect('user:login')
   

def add(request):
    if request.method == "POST":
        form = PhotoForm(request.POST,request.FILES)
        if form.is_valid():
            try:
                form.save()
                return redirect('photo_app:index')
            except:
                return HttpResponse('failed')

        else:
            print(form.errors)
            return HttpResponse("form not Valid")    

    else:    
        form =PhotoForm
        return render(request,"photo_app/addphoto.html",{'form':form})

def edit(request,id):
    photo =PhotoModel.objects.get(id=id)
    if request.method == "POST":
        form = PhotoForm(request.POST,request.FILES, instance=photo)
        if form.is_valid():
            try:
                form.save()
                return redirect('photo_app:index')
            except:
                return HttpResponse('failed')

        else:
            print(form.errors)
            return HttpResponse("form not Valid")    

    else:    
        form =PhotoForm
        return render(request,"photo_app/editphoto.html",{'form':form})

def profile(request):
    if 'id' in request.session:
        user_id=request.session['id']
        upload = PhotoModel.objects.filter(upload_by=user_id)
        user= UserModel.objects.get(id=user_id)
        dict={'upload':upload, 'user':user}
        return render(request,'photo_app/profile.html',dict)
    else:
        return redirect('user:login')

def delete(request,id):
    photo = PhotoModel.objects.get(id=id)
    photo.delete()
    return redirect('photo_app:profile')

def profile_edit(request):
    return render(request,'photo_app/profile_edit.html')

def search(request):
    if 'id' not in request.session:
        return redirect('user:login')

    userid= request.session.get('id',id)

    if request.method == 'GET':
        query= request.GET.get('q',None)
        if query:
            print(query)
            result = UserModel.objects.filter(username__contains=query)
            print(result)
            d={
                'profile': result,
                'query': query
            }
            return render(request,'photo_app/search_results.html',d)
        else:
            return redirect('photo_app:index')
    else:
        return redirect('photo_app:index')  

user_app/views.py
from django.shortcuts import render, redirect
from .models import UserModel
from django.http import HttpResponse



# Create your views here.

def display(request):
    return render(request,'user_app/display.html')

def logout(request):
    request.session.flush()
    return redirect('user:login')

def login(request):
    if request.method=='POST':
        e=request.POST.get('email')
        p=request.POST.get('pass')
        user = UserModel.objects.filter(email=e,password=p)
        
        if(user.count()>0):
            for user in user:
                request.session['email']=user.email
                request.session['id']=user.id
                request.session['username'] = user.username
                return redirect('photo_app:index')

        else:
            return HttpResponse("wrong Crdentials")
    else:
        return render(request,'user_app/login.html')
     

photo_app/templates/photo_app/addphoto.html
{% extends "photo_app/base.html"%}
{%block title %}
 index
 {% endblock %} 
 {% block content %}
 <form  action="" method="POST" enctype="multipart/form-data">
     {% csrf_token %}
      Captions:<input type="text" name="caption" placeholder="Enter the Photo Captions" style="height:150px; width:50%;"><br>
      Upload Photo:<input type="file" name="photo"><br>
      <input type="hidden" name="likes" value="0"><br>
      <input type="hidden" name="User" value="{{request.session.id}}"><br>
     <input type="submit" value="Upload">
 </form>
  
 
  {% endblock %}

photo_app/templates/photo_app/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Feed | Instaclone</title>
        <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
        <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon">
        <link href="{% static 'css/style.css' %}" rel="stylesheet">
        <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    </head> 
    <body>
        <nav class="navigation">
            <a href="feed.html">
                <img 
                    src="{% static 'images/navLogo.png' %}"
                    alt="logo"
                    title="logo"
                    class="navigation__logo"
                />
            </a>
            <div class="navigation__search-container">
                <i class="fa fa-search"></i>
                <input type="text" placeholder="Search">
            </div>
            <div class="navigation__icons">
                <a href="explore.html" class="navigation__link">
                    <i class="fa fa-compass"></i>
                </a>
                <a href="#" class="navigation__link">
                    <i class="fa fa-heart-o"></i>
                </a>
                <a href="{%url 'photo_app:profile' %}" class="navigation__link">
                    <i class="fa fa-user-o"></i>
                </a>
            </div>
        </nav>
        {% block main_content%}
        {% endblock %}
        <footer class="footer">
            <nav class="footer__nav">
                <ul class="footer__list">
                    <li class="footer__list-item"><a href="#" class="footer__link">about us</a></li>
                    <li class="footer__list-item"><a href="#" class="footer__link">support</a></li>
                    <li class="footer__list-item"><a href="#" class="footer__link">blog</a></li>
                    <li class="footer__list-item"><a href="#" class="footer__link">press</a></li>
                    <li class="footer__list-item"><a href="#" class="footer__link">api</a></li>
                    <li class="footer__list-item"><a href="#" class="footer__link">jobs</a></li>
                    <li class="footer__list-item"><a href="#" class="footer__link">privacy</a></li>
                    <li class="footer__list-item"><a href="#" class="footer__link">terms</a></li>
                    <li class="footer__list-item"><a href="#" class="footer__link">directory</a></li>
                    <li class="footer__list-item"><a href="#" class="footer__link">language</a></li>
                </ul>
            </nav>
            <span class="footer__copyright">© 2017 instagram</span>
        </footer>
        <script
  src="https://code.jquery.com/jquery-3.2.1.min.js"
  integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
  crossorigin="anonymous"></script>
        <script src="{% static 'js/app.js'%}"></script>
    </body>
</html>

photo_app/templates/photo_app/box-model.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Box Model</title>
    <style>
        html{
            height: 100%;
        }
        body{
            margin:0;
            background: red;
            height: 100%;
        }
        .parent{
            height: 100%;
            width:100%;
            background-color: blue;
            padding: 30px;
            box-sizing: border-box;
            display: flex;
            justify-content:space-between;
            align-items:stretch;
        }
        .child{
            width:100px;
            background-color: pink;
            border:2px solid red;
            height:100px;
        }
        #one{
            align-self:flex-start;
        }
        #two{
            align-self:center; 
        }
        #three{
            align-self: flex-end;
        }
    </style>
</head>
<body>
    <div class="parent">
        <div class="child" id="one">
        </div>
        <div class="child" id="two">
        </div>
        <div class="child" id="three">
        </div>
    </div>
</body>
</html>

photo_app/templates/photo_app/editphoto.html
{% extends "photo_app/base.html"%}
{%block title %}
 index
 {% endblock %} 
 {% block content %}
 <form  action="" method="POST" enctype="multipart/form-data">
     {% csrf_token %}
      Captions:<input type="text" name="caption"   placeholder="Enter the Photo Captions" style="height:150px; width:50%;"><br>
      Upload Photo:<input type="file" name="photo" value="{{photo.photo.url}}"><br>
      <input type="hidden" name="likes" value="{{photo.likes}}"><br>
      <input type="hidden" name="User" value="{{request.session.id}}"><br>
     <input type="submit" value="Upload">
 </form>
  
 
  {% endblock %}

photo_app/templates/photo_app/examples.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Examples</title>
</head>
<body>
    <h1>Forms and Inputs</h1>
    <form>
        <input type="text">
        <input type="email">
        <input type="password">
        <input type="file" accept="image/*">
        <input type="color">
        <input type="date">
        <input type="range">
        <input type="radio">
        <input type="checkbox">
        <input type="number">
    </form>
    <h1>Lists</h1>
    <ul>
        <li>One</li>
        <li>Two</li>
        <li>Three</li>
    </ul>
    <ol>
        <li>One</li>
        <li>Two</li>
        <li>Three</li>
    </ol>
    <h1>EMMET Syntax</h1>
    <code>parent.className#idName>child+sibling</code>
    <xmp>
        <parent class="className" id="idName">
            <child></child>
            <sibling></sibling>
        </parent>
    </xmp>
    <h1>Radio Buttons</h1>
    <span>What are you?</span>
    <br />
    <label for="female">Female</label>
    <input id="female" type="radio" value="female" name="gender" checked>
    <br>
    <label for="male">Male</label>
    <input id="male"type="radio" value="male" name="gender">
</body>
</html>

photo_app/templates/photo_app/explore.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Explore | Instaclone</title>
        <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
        <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon">
        <link href="css/style.css" rel="stylesheet">
        <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    </head>
    <body>
        <nav class="navigation">
            <a href="feed.html">
                <img 
                    src="images/navLogo.png"
                    alt="logo"
                    title="logo"
                    class="navigation__logo"
                />
            </a>
            <div class="navigation__search-container">
                <i class="fa fa-search"></i>
                <input type="text" placeholder="Search">
            </div>
            <div class="navigation__icons">
                <a href="explore.html" class="navigation__link">
                    <i class="fa fa-compass"></i>
                </a>
                <a href="#" class="navigation__link">
                    <i class="fa fa-heart-o"></i>
                </a>
                <a href="profile.html" class="navigation__link">
                    <i class="fa fa-user-o"></i>
                </a>
            </div>
        </nav>
        <main class="explore">
            <section class="people">
                <ul class="people__list">
                    <li class="people__person">
                        <div class="people__column">
                            <div class="people__avatar-container">
                                <img 
                                    src="images/avatar.jpg"
                                    class="people__avatar"
                                />
                            </div>
                            <div class="people__info">
                                <span class="people__username">davidbeckham</span>
                                <span class="people__full-name">David Beckham</span>
                            </div>
                        </div>
                        <div class="people__column">
                            <a href="#">Follow</a>
                        </div>
                    </li>
                    <li class="people__person">
                        <div class="people__column">
                            <div class="people__avatar-container">
                                <img 
                                    src="images/avatar.jpg"
                                    class="people__avatar"
                                />
                            </div>
                            <div class="people__info">
                                <span class="people__username">davidbeckham
                                    <img src="images/verified.png" />
                                </span>
                                <span class="people__full-name">David Beckham</span>
                            </div>
                        </div>
                        <div class="people__column">
                            <a href="#">Follow</a>
                        </div>
                    </li>
                    <li class="people__person">
                        <div class="people__column">
                            <div class="people__avatar-container">
                                <img 
                                    src="images/avatar.jpg"
                                    class="people__avatar"
                                />
                            </div>
                            <div class="people__info">
                                <span class="people__username">davidbeckham</span>
                                <span class="people__full-name">David Beckham</span>
                            </div>
                        </div>
                        <div class="people__column">
                            <a href="#">Follow</a>
                        </div>
                    </li>
                    <li class="people__person">
                        <div class="people__column">
                            <div class="people__avatar-container">
                                <img 
                                    src="images/avatar.jpg"
                                    class="people__avatar"
                                />
                            </div>
                            <div class="people__info">
                                <span class="people__username">davidbeckham</span>
                                <span class="people__full-name">David Beckham</span>
                            </div>
                        </div>
                        <div class="people__column">
                            <a href="#">Follow</a>
                        </div>
                    </li>
                </ul>
            </section>
        </main>
        <footer class="footer">
            <nav class="footer__nav">
                <ul class="footer__list">
                    <li class="footer__list-item"><a href="#" class="footer__link">about us</a></li>
                    <li class="footer__list-item"><a href="#" class="footer__link">support</a></li>
                    <li class="footer__list-item"><a href="#" class="footer__link">blog</a></li>
                    <li class="footer__list-item"><a href="#" class="footer__link">press</a></li>
                    <li class="footer__list-item"><a href="#" class="footer__link">api</a></li>
                    <li class="footer__list-item"><a href="#" class="footer__link">jobs</a></li>
                    <li class="footer__list-item"><a href="#" class="footer__link">privacy</a></li>
                    <li class="footer__list-item"><a href="#" class="footer__link">terms</a></li>
                    <li class="footer__list-item"><a href="#" class="footer__link">directory</a></li>
                    <li class="footer__list-item"><a href="#" class="footer__link">language</a></li>
                </ul>
            </nav>
            <span class="footer__copyright">© 2017 instagram</span>
        </footer>
        <script
  src="https://code.jquery.com/jquery-3.2.1.min.js"
  integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
  crossorigin="anonymous"></script>
        <script src="js/app.js"></script>
    </body>
</html>

photo_app/templates/photo_app/image-detail.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Image Detail | Instaclone</title>
        <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
        <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon">
        <link href="css/style.css" rel="stylesheet">
        <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    </head>
    <body>
        <nav class="navigation">
            <a href="feed.html">
                <img 
                    src="images/navLogo.png"
                    alt="logo"
                    title="logo"
                    class="navigation__logo"
                />
            </a>
            <div class="navigation__search-container">
                <i class="fa fa-search"></i>
                <input type="text" placeholder="Search">
            </div>
            <div class="navigation__icons">
                <a href="explore.html" class="navigation__link">
                    <i class="fa fa-compass"></i>
                </a>
                <a href="#" class="navigation__link">
                    <i class="fa fa-heart-o"></i>
                </a>
                <a href="profile.html" class="navigation__link">
                    <i class="fa fa-user-o"></i>
                </a>
            </div>
        </nav>
        <main class="image-detail">
            <section class="image">
                <div class="image__file-container">
                    <img 
                        src="images/feedPhoto.jpg"
                        class="image__file"
                    />
                </div>
                <div class="image__info">
                    <header class="image__header">
                        <div class="image__avatar-container">
                            <img 
                                src="images/avatar.jpg"
                                class="image__avatar"
                            />
                        </div>
                        <div class="image__info">
                            <span class="image__author">serranoarevalo</span>
                            <span class="image__location">The Fat Policeman, Budapest</span>
                        </div>
                    </header>
                    <ul class="image__comments">
                        <li class="image__comment">
                            <span class="image__comment-author">serranoarevalo</span> Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                        </li>
                    </ul>
                    <div class="image__actions">
                        <span class="image__action">
                            <i class="fa fa-heart-o fa-lg"></i>
                        </span>
                        <span class="image__action">
                            <i class="fa fa-comment-o fa-lg"></i>
                        </span>
                    </div>
                    <span class="image__likes">260 likes</span>
                    <span class="image__date">October 30, 2016</span>
                    <div class="image__add-comment">
                        <textarea class="image__textarea"></textarea>
                        <i class="fa fa-ellipsis-h"></i>
                    </div>
                </div>
            </section>
        </main>
        <footer class="footer">
            <nav class="footer__nav">
                <ul class="footer__list">
                    <li class="footer__list-item"><a href="#" class="footer__link">about us</a></li>
                    <li class="footer__list-item"><a href="#" class="footer__link">support</a></li>
                    <li class="footer__list-item"><a href="#" class="footer__link">blog</a></li>
                    <li class="footer__list-item"><a href="#" class="footer__link">press</a></li>
                    <li class="footer__list-item"><a href="#" class="footer__link">api</a></li>
                    <li class="footer__list-item"><a href="#" class="footer__link">jobs</a></li>
                    <li class="footer__list-item"><a href="#" class="footer__link">privacy</a></li>
                    <li class="footer__list-item"><a href="#" class="footer__link">terms</a></li>
                    <li class="footer__list-item"><a href="#" class="footer__link">directory</a></li>
                    <li class="footer__list-item"><a href="#" class="footer__link">language</a></li>
                </ul>
            </nav>
            <span class="footer__copyright">© 2017 instagram</span>
        </footer>
        <script
  src="https://code.jquery.com/jquery-3.2.1.min.js"
  integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
  crossorigin="anonymous"></script>
        <script src="js/app.js"></script>
    </body>
</html>

photo_app/templates/photo_app/profile.html
{% load static %}
{% block main_content %}
<main class="profile-container">
    <section class="profile">
        <header class="profile__header">
            <div class="profile__avatar-container">
                <img 
                    src="{% static 'images/avatar.jpg' %}"
                    class="profile__avatar"
                />
            </div>
            <div class="profile__info">
                <div class="profile__name">
                    <h1 class="profile__title"></h1>
                    <a href="{% url 'photo_app:profile_edit' %}" class="profile__button u-fat-text">Edit profile</a>
                    <i class="fa fa-cog fa-2x" id="cog"></i>
                </div>
                <ul class="profile__numbers">
                    <li class="profile__posts">
                        <span class="profile__number u-fat-text">10</span> posts
                    </li>
                    <li class="profile__followers">
                        <span class="profile__number u-fat-text">40</span> followers
                    </li>
                    <li class="profile__following">
                        <span class="profile__number u-fat-text">134</span> following
                    </li>
                </ul>
                <div class="profile__bio">
                    <span class="profile__full-name u-fat-text">Nicolás Serrano Arévalo</span>
                    <p class="profile__full-bio">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fugit rerum consequuntur aperiam, dicta delectus nihil voluptas explicabo sapiente quisquam. Eius ipsam asperiores excepturi maiores, atque voluptatum sed fuga esse molestiae.</p>
                    <a href="http://serranoarevalo.com" class="profile__link u-fat-text">serranoarevalo.com</a>
                </div>
            </div>
        </header>
        <div class="profile__pictures">
            <a href="image-detail.html" class="profile-picture">
                <img
                    src="{% static 'images/feedPhoto.jpg' %}"
                    class="profile-picture__picture"
                />
                <div class="profile-picture__overlay">
                    <span class="profile-picture__number">
                        <i class="fa fa-heart"></i> 450
                    </span>
                    <span class="profile-picture__number">
                        <i class="fa fa-comment"></i> 39
                    </span>
                </div>
            </a>
            <a href="image-detail.html" class="profile-picture">
                <img
                    src="{% static 'images/feedPhoto.jpg' %}"
                    class="profile-picture__picture"
                />
                <div class="profile-picture__overlay">
                    <span class="profile-picture__number">
                        <i class="fa fa-heart"></i> 450
                    </span>
                    <span class="profile-picture__number">
                        <i class="fa fa-comment"></i> 39
                    </span>
                </div>
            </a>
            <a href="image-detail.html" class="profile-picture">
                <img
                    src="{% static 'images/feedPhoto.jpg' %}"
                    class="profile-picture__picture"
                />
                <div class="profile-picture__overlay">
                    <span class="profile-picture__number">
                        <i class="fa fa-heart"></i> 450
                    </span>
                    <span class="profile-picture__number">
                        <i class="fa fa-comment"></i> 39
                    </span>
                </div>
            </a>
            <a href="image-detail.html" class="profile-picture">
                <img
                    src="{% static 'images/feedPhoto.jpg' %}"
                    class="profile-picture__picture"
                />
                <div class="profile-picture__overlay">
                    <span class="profile-picture__number">
                        <i class="fa fa-heart"></i> 450
                    </span>
                    <span class="profile-picture__number">
                        <i class="fa fa-comment"></i> 39
                    </span>
                </div>
            </a>
            <a href="image-detail.html" class="profile-picture">
                <img
                    src="{% static 'images/feedPhoto.jpg' %}"
                    class="profile-picture__picture"
                />
                <div class="profile-picture__overlay">
                    <span class="profile-picture__number">
                        <i class="fa fa-heart"></i> 450
                    </span>
                    <span class="profile-picture__number">
                        <i class="fa fa-comment"></i> 39
                    </span>
                </div>
            </a>
            <a href="image-detail.html" class="profile-picture">
                <img
                    src="{% static 'images/feedPhoto.jpg' %}"
                    class="profile-picture__picture"
                />
                <div class="profile-picture__overlay">
                    <span class="profile-picture__number">
                        <i class="fa fa-heart"></i> 450
                    </span>
                    <span class="profile-picture__number">
                        <i class="fa fa-comment"></i> 39
                    </span>
                </div>
            </a>
        </div>
    </section>
</main>
{% endblock %}

photo_app/templates/photo_app/search_results.html
{% extends 'photo_app/base.html' %}

{% block main_content %}

<main class="explore">
    <section class="people">
        <ul class="people__list">
            {% for user in profile %}
            <li class="people__person">
                <div class="people__column">
                    <div class="people__avatar-container">
                        <img 
                            src="{{ user.profile_pic.url}}"
                            class="people__avatar"
                        />
                    </div>
                    <div class="people__info">
                        <span class="people__username">{{user.username}}</span>
                        <span class="people__full-name">{{user.name}}</span>
                    </div>
                </div>
                <div class="people__column">
                    <a href="#">Follow</a>
                </div>
            </li>
            {% endfor %}
        </ul>
    </section>
</main>
{% endblock %}

user_app/templates/user_app/display.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Welcome</title>
</head>
<body>
    <h1> Hello User welcome</h1>
</body>
</html>